/// Message types for the Resonance application.
use crate::state::{ClipEdge, PunchDragTarget, ViewMode};
use resonance_audio::types::{ClipId, PluginInstanceId, ScannedPlugin, TrackId};

#[derive(Debug, Clone)]
pub(crate) enum Message {
    Play,
    Pause,
    Stop,
    SkipBack,
    SkipForward,
    AddTrack,
    RemoveTrack(TrackId),
    SetTrackVolume(TrackId, f32),
    SetTrackPan(TrackId, f32),
    SetMasterVolume(f32),
    ToggleMute(TrackId),
    ToggleSolo(TrackId),
    ImportFile(TrackId),
    FileSelected(TrackId, Option<String>),
    DeleteClip(ClipId),
    ZoomIn,
    ZoomOut,
    Tick,
    ToggleRecordArm(TrackId),
    ToggleMonitor(TrackId),
    ToggleTrackMono(TrackId),
    SetTrackInputDevice(TrackId, Option<String>),
    SetBpm(f32),
    ToggleMetronome,
    CycleTimeSignature,
    ScrollX(f32),
    ScrollY(f32),
    AddPluginToTrack(TrackId, ScannedPlugin),
    RemovePluginFromTrack(TrackId, PluginInstanceId),
    TogglePluginPanel(PluginInstanceId),
    SetPluginParam(PluginInstanceId, u32, f64),
    DrumPadSelect(PluginInstanceId, usize),
    PluginBrowseFile(PluginInstanceId),
    PluginFileSelected(PluginInstanceId, Option<String>),
    PluginPrevFile(PluginInstanceId),
    PluginNextFile(PluginInstanceId),
    SwitchView(ViewMode),
    OpenSettings,
    CloseSettings,
    DismissError,
    TogglePunch,
    #[allow(dead_code)] // reserved for direct punch position entry UI
    SetPunchIn(u64),
    #[allow(dead_code)] // reserved for direct punch position entry UI
    SetPunchOut(u64),
    StartPunchDrag(PunchDragTarget),
    UpdatePunchDrag(f32),
    EndPunchDrag,
    SelectClip(Option<ClipId>),
    StartClipDrag { clip_id: ClipId, grab_offset_x: f32, start_x: f32, start_y: f32 },
    UpdateClipDrag(f32, f32),
    EndClipDrag,
    StartClipTrim { clip_id: ClipId, edge: ClipEdge, anchor_x: f32 },
    UpdateClipTrim(f32),
    EndClipTrim,
    PluginFileScanComplete(PluginInstanceId, Option<String>, Vec<String>),
    ViewportWidth(f32),
}
