/// Message types for the Resonance application.
use crate::compose::ComposeMessage;
use crate::project::LoadedProject;
use crate::state::{ClipEdge, InstrumentIcon, InstrumentType, PunchDragTarget, ViewMode};
use resonance_audio::types::{
    BusId, ClipId, PluginInstanceId, ScannedPlugin, TrackId, TrackOutput,
};

#[derive(Debug, Clone)]
pub(crate) enum Message {
    Compose(ComposeMessage),
    Play,
    Record,
    Pause,
    Stop,
    SkipBack,
    SkipForward,
    /// Move the playhead to the given sample position (ruler click, etc.).
    SeekToSample(u64),
    AddTrack,
    RemoveTrack(TrackId),
    SetTrackVolume(TrackId, f32),
    SetTrackPan(TrackId, f32),
    SetMasterVolume(f32),
    ToggleMute(TrackId),
    ToggleSolo(TrackId),
    #[allow(dead_code)] // handler retained for a future import entry point (menu/drag-drop)
    ImportFile(TrackId),
    FileSelected(TrackId, Option<String>),
    DeleteClip(ClipId),
    ZoomIn,
    ZoomOut,
    Tick,
    ToggleRecordArm(TrackId),
    ToggleMonitor(TrackId),
    ToggleTrackMono(TrackId),
    /// Rename a track (edited from the Compose instrument details panel).
    SetTrackName(TrackId, String),
    /// Change an instrument track's sub-type (synth vs drum).
    SetInstrumentType(TrackId, InstrumentType),
    /// Change an instrument track's display icon.
    SetInstrumentIcon(TrackId, InstrumentIcon),
    SetTrackInputDevice(TrackId, Option<String>),
    SetBpmText(String),
    CommitBpm,
    ToggleMetronome,
    CyclePrecountBars,
    CycleTimeSignature,
    ScrollX(f32),
    ScrollY(f32),
    AddPluginToTrack(TrackId, ScannedPlugin),
    RemovePluginFromTrack(TrackId, PluginInstanceId),
    TogglePluginPanel(PluginInstanceId),
    SetPluginParam(PluginInstanceId, u32, f64),
    /// Open the plugin's editor window (CLAP_EXT_GUI).
    OpenPluginEditor(PluginInstanceId),
    /// Close the plugin's editor window.
    ClosePluginEditor(PluginInstanceId),
    PluginBrowseFile(PluginInstanceId),
    PluginFileSelected(PluginInstanceId, Option<String>),
    PluginPrevFile(PluginInstanceId),
    PluginNextFile(PluginInstanceId),
    SwitchView(ViewMode),
    OpenSettings,
    CloseSettings,
    OpenAddTrackMenu,
    CloseAddTrackMenu,
    DismissError,
    TogglePunch,
    #[allow(dead_code)] // reserved for direct punch position entry UI
    SetPunchIn(u64),
    #[allow(dead_code)] // reserved for direct punch position entry UI
    SetPunchOut(u64),
    StartPunchDrag(PunchDragTarget),
    UpdatePunchDrag(f32),
    EndPunchDrag,
    SelectClip(Option<ClipId>),
    StartClipDrag { clip_id: ClipId, grab_offset_x: f32, start_x: f32, start_y: f32 },
    UpdateClipDrag(f32, f32),
    EndClipDrag,
    StartClipTrim { clip_id: ClipId, edge: ClipEdge, anchor_x: f32 },
    UpdateClipTrim(f32),
    EndClipTrim,
    PluginFileScanComplete(PluginInstanceId, Option<String>, Vec<String>),
    ViewportWidth(f32),
    TimelineContentSize(f32, f32),
    ScrollToX(f32),
    ScrollToY(f32),
    BounceToWav,
    BouncePathSelected(Option<String>),
    SaveProject,
    SaveProjectAs,
    OpenProject,
    SavePathSelected(Option<String>),
    OpenPathSelected(Option<String>),
    ProjectSaved(Result<(), String>),
    ProjectLoaded(Result<Box<LoadedProject>, String>),
    AddInstrumentTrack,
    #[allow(dead_code)] // handler retained for a future MIDI clip creation entry point
    CreateMidiClip(TrackId),
    DeleteMidiClip(ClipId),
    StartMidiClipDrag { clip_id: ClipId, grab_offset_x: f32, start_x: f32, start_y: f32 },
    UpdateMidiClipDrag(f32, f32),
    EndMidiClipDrag,
    StartMidiClipTrim { clip_id: ClipId, edge: ClipEdge, anchor_x: f32 },
    UpdateMidiClipTrim(f32),
    EndMidiClipTrim,
    // MIDI piano roll editor messages
    OpenMidiEditor(ClipId),
    /// Open the currently selected MIDI clip (if any) in the piano roll editor.
    OpenSelectedMidiClip,
    CloseMidiEditor,
    MidiEditorAddNote { clip_id: ClipId, note: u8, start_tick: u64, duration_ticks: u64, velocity: f32 },
    MidiEditorRemoveNote { clip_id: ClipId, note_index: usize },
    MidiEditorMoveNote { clip_id: ClipId, note_index: usize, new_start_tick: u64, new_note: u8 },
    MidiEditorResizeNote { clip_id: ClipId, note_index: usize, new_duration_ticks: u64 },
    MidiEditorSelectNote { note_index: Option<usize> },
    MidiEditorPreviewNote(TrackId, u8),
    MidiEditorStopPreview(TrackId, u8),
    MidiEditorScrollX(f32),
    MidiEditorScrollY(f32),

    // -- Bus messages --
    AddBus,
    RemoveBus(BusId),
    SetBusVolume(BusId, f32),
    SetBusPan(BusId, f32),
    ToggleBusMute(BusId),
    SetTrackOutput(TrackId, TrackOutput),
    AddPluginToBus(BusId, ScannedPlugin),
    RemovePluginFromBus(BusId, PluginInstanceId),
}
