/// Reusable DSP building blocks for Resonance plugins.
mod biquad;
mod convolver;
mod db;
mod dc_blocker;
pub mod decorrelate;
pub mod deharsh;
mod delay;
mod denormal;
pub mod detune;
pub mod dynamics;
pub mod eq;
mod filter;
pub mod formant;
mod granular;
pub mod hysteresis;
mod interp;
mod lfo;
mod oversample;
mod pan;
pub mod pitch;
pub mod pitch_rt;
mod rng;
pub mod saturate;
pub mod segment;
mod shaper;
mod stereo;
mod swap_fader;
pub mod tape;
mod timestretch;
pub mod tempo;
pub mod transformer;
mod window;

pub use biquad::{Biquad, BiquadCoeffs};
pub use convolver::FftConvolver;
pub use db::{db_to_linear, linear_to_db, MIN_DB};
pub use dc_blocker::DcBlocker;
pub use decorrelate::{AllpassDecorrelator, VelvetDecorrelator};
pub use deharsh::{ResonanceSuppressor, SuppressorConfig, SuppressorMode};
pub use delay::DelayLine;
pub use denormal::flush_denormals;
pub use detune::DopplerShifter;
pub use dynamics::{soft_knee_gain_reduction_db, Ballistics};
pub use eq::BandType;
pub use filter::OnePole;
pub use formant::{formant_pitch_shift, FormantShifter};
pub use hysteresis::{Hysteresis, HysteresisSolver, JaParams};
pub use granular::{GrainEngine, GrainParams, GrainView, InterpQuality, SchedulerMode, MAX_GRAINS};
pub use interp::{
    BandlimitedReader, bspline6, hermite4, lagrange6, read_bspline6_wrapped, read_hermite_wrapped,
    read_lagrange6_wrapped, read_linear_wrapped,
};
pub use lfo::Lfo;
pub use oversample::{halfband_coefs, Halfband, OversampleFactor, Oversampler};
pub use pan::{constant_power_pan, stereo_balance};
pub use pitch::{detect_f0, F0Config, F0Frame, YinDetector};
pub use pitch_rt::{PitchEstimate, PitchTracker};
pub use rng::SimpleRng;
pub use saturate::{Adaa1, Curve};
pub use segment::{segment_notes, NoteBlob, SegmentConfig};
pub use shaper::tanh_fast;
pub use stereo::{apply_balance, apply_width, ms_decode, ms_encode, StereoRotation};
pub use swap_fader::SwapFader;
pub use tape::{Flutter, HeadBump, HfLoss};
pub use tempo::{detect_tempo, detect_tempo_default, fold_bpm, TempoConfig, TempoEstimate};
pub use timestretch::{StretchAlgorithm, TimeStretch};
pub use transformer::{EmphasisPair, LfWeightedDrive};
pub use window::{fill_hann_window, hann_window, WindowMorph};
