//! Real-time "bounce in place" for instrument tracks driven by an
//! external MIDI device. Internal-synth tracks render via the offline
//! [`super::bounce::to_audio_clip`] entry point; external-MIDI tracks
//! can't be rendered offline because the audio is generated by hardware
//! that we have to listen to in real time.
//!
//! The flow:
//!
//! 1. Validate inputs (source has MIDI, project dir is set, transport
//!    stopped, target track exists).
//! 2. Snapshot every track's `muted()` state.
//! 3. Mute every non-source track (this also stops their hardware MIDI
//!    Out — see `engine/midi.rs` poll filter), unmute the source.
//! 4. Configure the target audio track's input device + port, arm it.
//! 5. Seek to the source's first MIDI start and start the recording
//!    stream via [`super::transport::begin_recording_stream`].
//! 6. Stash a [`PendingBounce`] in [`HandlerState`] so the engine
//!    control loop's [`poll_pending_bounce`] hook can stop the run when
//!    the playhead crosses the end-of-MIDI + tail.
//!
//! On stop:
//! - Pause the transport (which finalizes the recording — clip arrives
//!   on the app side via the existing `RecordingFinished` event).
//! - Restore the mute snapshot, mute the source, disarm the target.
//! - Emit `AudioEvent::TrackBounceCompleted` so the app reflects the
//!   source mute and reorders the new track.

use std::collections::HashMap;
use std::sync::atomic::Ordering;

use crate::types::*;

use super::bounce_common::midi_render_range;
use super::thread::{HandlerCtx, HandlerState};

/// State that survives across engine-thread iterations until the
/// realtime bounce reaches its scheduled stop point.
pub(crate) struct PendingBounce {
    pub source_track_id: TrackId,
    pub target_track_id: TrackId,
    /// Sample the bounce started rendering from. Stored alongside
    /// `stop_at` so the progress poll can compute fraction
    /// `(playhead - start_at) / (stop_at - start_at)`.
    pub start_at: SamplePos,
    /// Sample at which the engine should pause the transport and
    /// finalize the recording. Computed as the last MIDI clip end on
    /// the source plus a fixed tail.
    pub stop_at: SamplePos,
    /// Mute state of every track at the time the bounce started, keyed
    /// by track id. Restored when the bounce finishes (or fails) so the
    /// user's mix is left as it was.
    pub mute_snapshot: HashMap<TrackId, bool>,
    /// Target track's previous `input_device_name`, captured before we
    /// overwrite it with the user-picked bounce input. Restored alongside
    /// the mute snapshot so re-running a bounce on the same target track
    /// doesn't permanently rewrite its input.
    pub prev_target_input_device: Option<String>,
    /// Last percentage emitted as a `BounceProgress` event, so the
    /// poll only fires fresh events when fraction changes by ≥1%.
    pub last_emitted_pct: i32,
}

pub(crate) fn handle_bounce_track_realtime(
    ctx: &HandlerCtx,
    state: &mut HandlerState,
    source_track_id: TrackId,
    target_track_id: TrackId,
    input_device_name: String,
    input_port_index: u16,
    mono: bool,
) {
    if ctx.shared.playing.load(Ordering::Relaxed) {
        let _ = ctx.event_tx.send(AudioEvent::TrackBounceError(
            "Stop transport before bouncing".into(),
        ));
        return;
    }
    if state.project_dir.is_none() {
        let _ = ctx.event_tx.send(AudioEvent::TrackBounceError(
            "Save the project before bouncing — recording needs a project directory.".into(),
        ));
        return;
    }
    if state.pending_bounce.is_some() {
        let _ = ctx.event_tx.send(AudioEvent::TrackBounceError(
            "Another bounce is already in progress".into(),
        ));
        return;
    }

    // Clear any stale cancel flag from a prior run before we start —
    // the same atomic gates the offline renderer and signals the
    // realtime path. A leftover `true` would abort the run on the
    // very first poll.
    ctx.shared.bounce_cancel.store(false, Ordering::Relaxed);

    // Compute render range — punch-in/out loop wins, otherwise the
    // source track's MIDI extent + tail.
    let (render_start, render_end) = match midi_render_range(
        ctx.midi_clips,
        ctx.tempo_map,
        ctx.shared,
        source_track_id,
        ctx.sample_rate,
    ) {
        Ok(range) => range,
        Err(msg) => {
            let _ = ctx.event_tx.send(AudioEvent::TrackBounceError(msg.into()));
            return;
        }
    };

    // Validate that source + target both exist, and that the source is
    // an instrument track (otherwise there's nothing to bounce).
    {
        let tracks_guard = ctx.tracks.read();
        let Some(source) = tracks_guard.get(&source_track_id) else {
            let _ = ctx.event_tx.send(AudioEvent::TrackBounceError(
                "Source track not found".into(),
            ));
            return;
        };
        if source.track_type != TrackType::Instrument {
            let _ = ctx.event_tx.send(AudioEvent::TrackBounceError(
                "Bounce in place is only available on instrument tracks".into(),
            ));
            return;
        }
        if !tracks_guard.contains_key(&target_track_id) {
            let _ = ctx.event_tx.send(AudioEvent::TrackBounceError(
                "Target track not found".into(),
            ));
            return;
        }
    }

    // Snapshot mute state of every track. Build the set of "in-filter"
    // ids (source + sub-tracks of source) so we know which to leave
    // unmuted during the bounce.
    let (mute_snapshot, in_filter): (HashMap<TrackId, bool>, Vec<TrackId>) = {
        let tracks_guard = ctx.tracks.read();
        let snapshot: HashMap<TrackId, bool> = tracks_guard
            .values()
            .map(|t| (t.id, t.muted()))
            .collect();
        let mut allow = vec![source_track_id];
        for t in tracks_guard.values() {
            if let Some((parent, _)) = t.sub_track_of {
                if parent == source_track_id {
                    allow.push(t.id);
                }
            }
        }
        (snapshot, allow)
    };

    // Configure target track's input + arm it. Mute every other track
    // so its MIDI Out and audio contribution stay silent during the
    // bounce (the mixer's existing mute path covers audio; the muted
    // check added in `engine/midi.rs:744` covers MIDI Out). Snapshot the
    // target's previous input device name so we can restore it when the
    // bounce ends.
    let prev_target_input_device = {
        let tracks_guard = ctx.tracks.read();
        let prev = tracks_guard
            .get(&target_track_id)
            .and_then(|t| t.input_device_name.load_full().map(|a| (*a).clone()));
        if let Some(target) = tracks_guard.get(&target_track_id) {
            target
                .input_device_name
                .store(Some(std::sync::Arc::new(input_device_name)));
        }
        prev
    };
    {
        let tracks_guard = ctx.tracks.read();
        for t in tracks_guard.values() {
            let allow = in_filter.contains(&t.id) || t.id == target_track_id;
            t.set_muted(!allow);
            if t.id == target_track_id {
                t.set_input_port(input_port_index);
                t.set_mono(mono);
                t.set_record_armed(true);
            } else if t.record_armed() {
                // Disarm any other track that happened to be armed so
                // we don't accidentally capture other inputs into them.
                t.set_record_armed(false);
            }
        }
    }

    // Seek transport to render_start.
    ctx.shared.playhead.store(render_start, Ordering::SeqCst);

    // Run the transport BEFORE opening the recording stream so
    // `handle_play` sees `was_playing == false` and emits the MIDI
    // clock Start/Continue (with SPP) for any external sequencer or
    // arpeggiator the source drives. `begin_recording_stream` sets
    // `playing = true` itself, which would short-circuit the clock
    // path if it ran first.
    super::transport::handle_play(ctx, state);

    // Open the recording stream. This allocates the clip id, opens the
    // WAV writer, builds the input stream — same path as a normal
    // Record press.
    super::transport::begin_recording_stream(ctx, state, render_start);

    // If begin_recording_stream failed (input device unavailable, etc.)
    // it emits AudioEvent::Error and leaves `state.rec.input_stream`
    // unset. Detect that and unwind so we don't leave the user's mix in
    // a half-bounced state.
    if state.rec.input_stream.is_none() {
        // Pause the transport we just started so the half-bounced state
        // doesn't leave the playhead drifting forward silently.
        super::transport::handle_pause(ctx, state);
        restore_after_bounce(
            ctx,
            &mute_snapshot,
            target_track_id,
            prev_target_input_device,
        );
        // Also surface a TrackBounceError; begin_recording_stream sent
        // a generic Error already, but the user's "bounce in place"
        // expectation gets the dedicated channel.
        let _ = ctx.event_tx.send(AudioEvent::TrackBounceError(
            "Failed to start recording for bounce — see audio engine error".into(),
        ));
        return;
    }

    // Surface the modal-driving 0% event up-front so the GUI shows a
    // populated progress bar immediately, before the playhead has
    // actually moved off `render_start`.
    let _ = ctx.event_tx.send(AudioEvent::BounceProgress { fraction: 0.0 });

    state.pending_bounce = Some(PendingBounce {
        source_track_id,
        target_track_id,
        start_at: render_start,
        stop_at: render_end,
        mute_snapshot,
        prev_target_input_device,
        last_emitted_pct: 0,
    });
}

/// Engine-loop hook: when a realtime bounce is pending and the playhead
/// has reached its end, pause the transport (which finalizes the
/// recording — clip arrives via `RecordingFinished`), restore mute
/// snapshot, mute the source, disarm the target, and emit
/// `TrackBounceCompleted`.
pub(crate) fn poll_pending_bounce(ctx: &HandlerCtx, state: &mut HandlerState) {
    // Cancel handling: `CancelBounce` flips `bounce_cancel` for both
    // the offline and realtime paths. The offline path checks it
    // between chunks; the realtime path checks it here, runs the
    // teardown, and emits `TrackBounceCancelled` so the app drops the
    // modal without showing an error banner.
    if state.pending_bounce.is_some()
        && ctx.shared.bounce_cancel.load(Ordering::Relaxed)
    {
        ctx.shared.bounce_cancel.store(false, Ordering::Relaxed);
        let bounce = state.pending_bounce.take().unwrap();
        super::transport::handle_pause(ctx, state);
        restore_after_bounce(
            ctx,
            &bounce.mute_snapshot,
            bounce.target_track_id,
            bounce.prev_target_input_device.clone(),
        );
        // Drop the freshly-added empty target track so the user's mix
        // ends up where it started (minus the rendered clip we just
        // discarded). The clip was emitted via `RecordingFinished`
        // during `handle_pause`'s `finalize_recording` if any audio
        // made it to disk; clean that up too.
        let removed_clip_ids: Vec<ClipId> = {
            let clips = ctx.clips.read();
            clips
                .iter()
                .filter(|c| c.track_id == bounce.target_track_id)
                .map(|c| c.id)
                .collect()
        };
        {
            let mut clips = ctx.clips.write();
            clips.retain(|c| c.track_id != bounce.target_track_id);
        }
        for clip_id in removed_clip_ids {
            let _ = ctx.event_tx.send(AudioEvent::ClipDeleted { clip_id });
        }
        let _ = ctx.tracks.write().shift_remove(&bounce.target_track_id);
        let _ = ctx.event_tx.send(AudioEvent::TrackRemoved {
            track_id: bounce.target_track_id,
        });
        let _ = ctx.event_tx.send(AudioEvent::TrackBounceCancelled {
            target_track_id: bounce.target_track_id,
        });
        return;
    }

    let Some(bounce) = state.pending_bounce.as_mut() else {
        return;
    };
    let playhead = ctx.shared.playhead.load(Ordering::Relaxed);

    // Emit progress at most once per integer percent — the audio
    // thread is advancing the playhead at sample rate, so this poll
    // would otherwise spam the GUI channel at engine cadence (~60 Hz).
    let span = bounce.stop_at.saturating_sub(bounce.start_at).max(1);
    let elapsed = playhead.saturating_sub(bounce.start_at).min(span);
    let pct = ((elapsed as f32 / span as f32) * 100.0) as i32;
    if pct > bounce.last_emitted_pct {
        bounce.last_emitted_pct = pct;
        let _ = ctx.event_tx.send(AudioEvent::BounceProgress {
            fraction: (pct as f32 / 100.0).min(1.0),
        });
    }

    if playhead < bounce.stop_at {
        return;
    }
    let bounce = state.pending_bounce.take().unwrap();

    // Snapshot frames captured + peak amplitude for the target track
    // before handle_pause drains and finalizes the recording state.
    // Two failure modes we want to surface clearly instead of silently
    // muting the source with nothing to play in its place:
    //
    //  - frames_captured == 0: the cpal input callback never fired, so
    //    the device the user picked isn't actually delivering frames
    //    (wrong device name, device unavailable, etc.).
    //  - peak below `SILENT_THRESHOLD`: the device is delivering frames
    //    but they're all near-zero, meaning the synth's audio return
    //    isn't actually connected to that input.
    const SILENT_THRESHOLD: f32 = 0.0001;
    let (frames_captured, peak_abs) = state
        .rec
        .buffers
        .get(&bounce.target_track_id)
        .map(|b| {
            let mut peak: f32 = 0.0;
            for (mn, mx) in &b.peaks {
                peak = peak.max(mn.abs()).max(mx.abs());
            }
            // Also consider the in-progress peak window so a recording
            // shorter than `WAVEFORM_PEAK_FRAMES` doesn't appear silent
            // just because no chunk closed yet.
            if b.peak_frames > 0 {
                peak = peak.max(b.peak_min.abs()).max(b.peak_max.abs());
            }
            (b.frames_written, peak)
        })
        .unwrap_or((0, 0.0));

    // Pause the transport — finalizes the recording stream and emits
    // `RecordingFinished` for every armed track.
    super::transport::handle_pause(ctx, state);

    restore_after_bounce(
        ctx,
        &bounce.mute_snapshot,
        bounce.target_track_id,
        bounce.prev_target_input_device.clone(),
    );

    if frames_captured == 0 {
        // No audio reached the WAV. Don't mute the source — the user
        // hasn't actually replaced its sound with anything yet.
        let _ = ctx.event_tx.send(AudioEvent::TrackBounceError(
            "Bounce captured no audio from the input device. Check that the picked device is the one your external instrument's audio output is wired to."
                .into(),
        ));
        return;
    }
    if peak_abs < SILENT_THRESHOLD {
        let _ = ctx.event_tx.send(AudioEvent::TrackBounceError(
            "Bounce recorded silence — the input device opened, but the signal level was effectively zero. Check the cabling between your external instrument and the picked input."
                .into(),
        ));
        return;
    }

    // Mute the source so subsequent playback uses the bounced audio,
    // not the live external instrument.
    {
        let tracks_guard = ctx.tracks.read();
        if let Some(source) = tracks_guard.get(&bounce.source_track_id) {
            source.set_muted(true);
        }
    }

    let _ = ctx.event_tx.send(AudioEvent::TrackBounceCompleted {
        source_track_id: bounce.source_track_id,
        target_track_id: bounce.target_track_id,
        clip: None,
    });
}

/// Reverse the `mute`/`record_armed`/`input_device_name` mutations that
/// `handle_bounce_track_realtime` made before the bounce started.
/// Shared by the failure unwind and the success-path completion so the
/// two can't drift apart. The audio-thread mute/record-arm fields are
/// atomics, so a read lock on `tracks` is enough.
fn restore_after_bounce(
    ctx: &HandlerCtx,
    mute_snapshot: &HashMap<TrackId, bool>,
    target_track_id: TrackId,
    prev_target_input_device: Option<String>,
) {
    let tracks_guard = ctx.tracks.read();
    for t in tracks_guard.values() {
        if let Some(prev) = mute_snapshot.get(&t.id) {
            t.set_muted(*prev);
        }
        if t.id == target_track_id {
            t.set_record_armed(false);
        }
    }
    if let Some(target) = tracks_guard.get(&target_track_id) {
        target
            .input_device_name
            .store(prev_target_input_device.map(std::sync::Arc::new));
    }
}
