//! Shared helpers and cached pick_list option vectors for the vocal
//! inspector groups.

use std::sync::OnceLock;

use iced::widget::{button, container, row, text, Space};
use iced::{alignment, Background, Border, Color, Element, Length};

use resonance_music_theory::{VocalMood, VocalPov, VoiceType};

use super::super::display_pick::display_pick;

use crate::message::*;
use crate::theme;

// ===========================================================================
// Cached pick_list option vectors.
// ===========================================================================
//
// `pick_list` takes the option list by value (a `Cow`-style slice). Rebuilding
// these every frame allocates a fresh `Vec<u8>` per dropdown; the inspector
// shows six of them, so that's six vec allocs per repaint while the user
// twiddles a slider. These statics are populated on first access and reused
// thereafter. See view-layer performance memory for the codebase rule.

pub(super) fn line_count_options() -> &'static [u8] {
    static V: OnceLock<Vec<u8>> = OnceLock::new();
    V.get_or_init(|| (1..=8).collect())
}
pub(super) fn syllable_min_options() -> &'static [u8] {
    static V: OnceLock<Vec<u8>> = OnceLock::new();
    V.get_or_init(|| (3..=20).collect())
}
pub(super) fn syllable_max_options() -> &'static [u8] {
    static V: OnceLock<Vec<u8>> = OnceLock::new();
    V.get_or_init(|| (3..=24).collect())
}
pub(super) fn range_low_options() -> &'static [u8] {
    static V: OnceLock<Vec<u8>> = OnceLock::new();
    V.get_or_init(|| (36..=72).collect())
}
pub(super) fn range_high_options() -> &'static [u8] {
    static V: OnceLock<Vec<u8>> = OnceLock::new();
    V.get_or_init(|| (48..=96).collect())
}
pub(super) fn phrase_length_options() -> &'static [u8] {
    static V: OnceLock<Vec<u8>> = OnceLock::new();
    V.get_or_init(|| (1..=8).collect())
}

// ===========================================================================
// Display newtypes for the three enum-backed dropdowns. The newtype is
// generated by the `display_pick!` macro along with its cached
// `Vec<NewType>` (populated from `Enum::ALL` on first access).
// ===========================================================================

display_pick!(MoodPick, VocalMood, as_str, mood_pick_options);
display_pick!(PovPick, VocalPov, as_str, pov_pick_options);
display_pick!(VoiceTypePick, VoiceType, as_str, voice_type_pick_options);

// ===========================================================================
// Style helpers
// ===========================================================================

pub(super) fn rail_dot_warm<'a>() -> Element<'a, Message> {
    container(Space::new().width(Length::Fixed(6.0)).height(Length::Fixed(6.0)))
        .style(|_| container::Style {
            background: Some(Background::Color(theme::WARM)),
            border: Border {
                color: theme::WARM,
                width: 0.0,
                radius: 3.0.into(),
            },
            ..Default::default()
        })
        .into()
}

pub(super) fn group_title<'a>(label: &'static str) -> Element<'a, Message> {
    row![
        rail_dot_warm(),
        text(label).size(11).font(theme::UI_FONT_SEMIBOLD).color(theme::WARM),
    ]
    .spacing(8)
    .align_y(alignment::Vertical::Center)
    .into()
}

pub(super) fn dim_label<'a>(s: impl Into<String>) -> Element<'a, Message> {
    text(s.into()).size(10).color(theme::TEXT_3).into()
}

pub(super) fn warm_chip_active<'a>(label: impl Into<String>) -> button::Button<'a, Message> {
    button(
        text(label.into())
            .size(10)
            .font(theme::UI_FONT_SEMIBOLD)
            .color(theme::WARM),
    )
    .padding([4, 8])
    .style(|_, status| {
        let bg = match status {
            button::Status::Hovered => Color { a: 0.24, ..theme::WARM },
            _ => Color { a: 0.18, ..theme::WARM },
        };
        button::Style {
            background: Some(Background::Color(bg)),
            text_color: theme::WARM,
            border: Border {
                color: theme::WARM,
                width: 1.0,
                radius: theme::RADIUS_SM.into(),
            },
            ..Default::default()
        }
    })
}

pub(super) fn warm_chip_inactive<'a>(label: impl Into<String>) -> button::Button<'a, Message> {
    button(text(label.into()).size(10).color(theme::TEXT_2))
        .padding([4, 8])
        .style(|_, status| {
            let bg = match status {
                button::Status::Hovered => theme::BG_3,
                _ => theme::BG_2,
            };
            button::Style {
                background: Some(Background::Color(bg)),
                text_color: theme::TEXT_2,
                border: Border {
                    color: theme::LINE_2,
                    width: 1.0,
                    radius: theme::RADIUS_SM.into(),
                },
                ..Default::default()
            }
        })
}

pub(super) fn chip<'a>(
    label: impl Into<String>,
    active: bool,
    on_press: Message,
) -> Element<'a, Message> {
    if active {
        warm_chip_active(label).on_press(on_press).into()
    } else {
        warm_chip_inactive(label).on_press(on_press).into()
    }
}

pub(super) fn group_card<'a>(content: Element<'a, Message>) -> Element<'a, Message> {
    container(content)
        .padding(12)
        .width(Length::Fill)
        .style(|_| container::Style {
            background: Some(Background::Color(theme::BG_2)),
            border: Border {
                color: theme::LINE_2,
                width: 1.0,
                radius: theme::RADIUS_XL.into(),
            },
            ..Default::default()
        })
        .into()
}

/// Unicode-sharp variant (`"F♯3"`) — this inspector's labels use `♯`,
/// not the ASCII `#` of [`resonance_music_theory::midi_note_name`].
pub(super) fn midi_to_name(n: u8) -> String {
    resonance_music_theory::midi_note_name_unicode(n)
}
